### ISSUE TITLE
BUG: Scanning QR from QR Vault

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/GordianSeedTool-iOS#51] opened 2021-05-26 03:16 UTC
I have 24 words used in the #SmartCustody book for demonstrations on steel and titanium. It is one of the first things I try on all wallets:

```
toe priority custom gauge jacket theme arrest bargain gloom wide ill fit eagle prepare capable fish limb cigar reform other priority speak rough imitate
```

When I import these seed words in GW to create a legacy hot wallet, the "backup info" for backing up the seed in UR results in:

ur:crypto-seed/oyadhdcxvlmdhhtndyfljsrtaxcsmdialbgosrpyvegyguspknrylyskckttgllepeoypebwgrtliooy

This does work import into UR Vault, it receives this text and can generate a QR code for it.

![Screenshot 2021-05-25 at 8 00 30 PM](https://user-images.githubusercontent.com/69103/119596607-5b546880-bd94-11eb-8abe-fe0b2c42b58b.jpeg)

HOWEVER, when I try to scan it with Guardian, I get:

![IMG_4190](https://user-images.githubusercontent.com/69103/119596787-acfcf300-bd94-11eb-87d3-6bdb2fe5e1c5.jpeg)

Nothing happens — no lockup, no error, a "pulse" as if it is scanning, but no scan. I can tap the "Done" button to cancel, but I can't import this ur:crypto-seed QR into Guardian.

I'm not clear if there is a bug in GW generation of the ur:crypto-seed, but if there is, UR Vault isn't seeing the error. If there is a bug in the crypto-seed, then Guardian should give me an error, not fail to scan.

If it is useful: I can import these 24 words into Guardian directly. It results in crypto-seed `8b206fb`, crypto-hdkey `1b0a3b7` and master key fingerprint `de584efd`. I note that the last master key `de584efd` Guardian does match the master key fingerprint in the xpub/xprv export of GW.

/cc @Fonta1n3

**Comment by wolfmcnally** [comment] 2021-05-28 07:19
This is not a problem with Guardian. There are two issues with the UR in the QR code above, one non-fatal and one fatal:

Non-fatal: The UR is in lower case. URs in QR codes should be all upper case.
Fatal: The encoded UR has three carriage returns after it. Whitespace is not allowed in URs.

@Fonta1n3 @ChristopherA

**Comment by ChristopherA** [comment] 2021-05-28 07:26
Please don’t close without adding issue or moving it to other repo.

**Comment by ChristopherA** [comment] 2021-05-28 07:29
Also, still a bug. No error message was given in GST when QR code fails.

**Comment by wolfmcnally** [comment] 2021-06-25 00:46
> Also, still a bug. No error message was given in GST when QR code fails.

Actually, not a bug. QR codes that include invalid characters are simply corrupt data.

**Comment by wolfmcnally** [comment] 2021-06-25 00:48
This appears to have been addressed by @Fonta1n3 , so I'm closing it again.

**Closed by wolfmcnally** 2021-06-25 00:48 UTC
